services:
   ml_frontbundle.validator.underonethousand:
     class: ML\FrontBundle\Validator\UnderOneThousandValidator
     arguments: [ '@ML\FrontBundle\CheckQuantity\MLCheckQuantity' ] # Mettre service moins 1000 resa
     tags:
       - { name: validator.constraint_validator, alias: ml_frontbundle_underonethousand }

   ml_frontbundle.date:
     class: ML\FrontBundle\Date\MLDate
     arguments: [ "@doctrine.orm.entity_manager", 1000 ]

   ML\FrontBundle\DateManager\MLDateManager:
     class: ML\FrontBundle\DateManager\MLDateManager
     arguments: [ "@doctrine.orm.entity_manager" ]


   ML\FrontBundle\FinalProcess\MLFinalProcess:
     class: ML\FrontBundle\FinalProcess\MLFinalProcess
     arguments: [ "@doctrine.orm.entity_manager", "@mailer", "@twig" ]

   ML\FrontBundle\CheckQuantity\MLCheckQuantity:
     class: ML\FrontBundle\CheckQuantity\MLCheckQuantity
     arguments:  [ "@doctrine.orm.entity_manager" ]
     tags:
      - { name: ml_frontbundle.checkquantity, alias: ml_frontbundle.checkquantity }

   ml_frontbundle.doctrine_listener.reservation_listener:
     class: ML\FrontBundle\DoctrineListener\ReservationListener
     #arguments: [ "@doctrine.orm.entity_manager" ]
     tags:
       - { name: doctrine.event_listener, event: onFlush }

   ML\FrontBundle\Service\TicketsPrice:
     class: ML\FrontBundle\Service\TicketsPrice
     arguments: [ "@file_locator" ]
     tags:
        - { name: mlfrontbundle_ticketsprice, alias: ml_frontbundle_ticketsprice } 
     #METTRE @KERNEL EN ARGUMENTS